# This is a basic workflow to help you get started with Actions

name: Basics

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  second-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Job running in parallel
      
  third-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Adds dependency on the second-job
    needs: second-job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Job running after the second-job secuentially
